"""XLSX-only column name constants, palette, style objects and column group definitions.

All symbols are re-exported from pipeline_xlsx via ``from ._xlsx_columns import *``.
"""
from __future__ import annotations

from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

from stack_protein_preparation.pipeline_state import (
    ALIGNMENT_DIRECTORY_COLUMN_NAME,
    AVAILABLE_MODELS_COLUMN_NAME,
    COMPONENTS_DIRECTORY_COLUMN_NAME,
    FASTA_DIRECTORY_COLUMN_NAME,
    FASTA_FILES_DONE_COLUMN_NAME,
    FILLER_DIRECTORY_COLUMN_NAME,
    FILLER_MODEL_PATH_COLUMN_NAME,
    FILLER_MODEL_SOURCE_COLUMN_NAME,
    FILLER_STATUS_COLUMN_NAME,
    GAP_SIZES_COLUMN_NAME,
    HAS_GAPS_COLUMN_NAME,
    HAS_LIGANDS_COLUMN_NAME,
    HAS_METALS_COLUMN_NAME,
    METALS_ION_TYPE_COLUMN_NAME,
    METALS_CLASS_COLUMN_NAME,
    METALS_MODEL_READY_COLUMN_NAME,
    HAS_NONSTANDARD_RESIDUES_COLUMN_NAME,
    INSERTION_CODES_DONE_COLUMN_NAME,
    INTERNAL_CAPPING_INPUT_PATH_COLUMN_NAME,
    INTERNAL_CAPPING_OUTPUT_PATH_COLUMN_NAME,
    INTERNAL_CAPPING_STATUS_COLUMN_NAME,
    METALL_PARAMS_DIRECTORY_COLUMN_NAME,
    METALL_PARAMS_MANIFEST_PATH_COLUMN_NAME,
    METALL_PARAMS_SITE_COUNT_COLUMN_NAME,
    METALL_PARAMS_STATUS_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_MANIFEST_PATH_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_N_RESIDUES_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_STATUS_COLUMN_NAME,
    N_GAPS_COLUMN_NAME,
    PDB_DIRECTORY_COLUMN_NAME,
    PDB_ID_COLUMN_NAME,
    PDB_SYNC_DONE_COLUMN_NAME,
    PREPARED_ALPHAFOLD_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_DIRECTORY_COLUMN_NAME,
    PREPARED_GAPS_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_MODELLER_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_ACTUAL_RANGE_COLUMN_NAME,
    PREPARED_STRUCTURE_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_PROTEIN_INPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_VARIANT_COLUMN_NAME,
    PROTONATION_INPUT_PATH_COLUMN_NAME,
    PROTONATION_INPUT_SOURCE_COLUMN_NAME,
    PROTONATION_OUTPUT_PATH_COLUMN_NAME,
    PROTONATION_STATUS_COLUMN_NAME,
    RANGE_COLUMN_NAME,
    RETAIN_ALPHAFOLD_VARIANT_COLUMN_NAME,
    RETAIN_GAPS_VARIANT_COLUMN_NAME,
    RETAIN_MODELLER_VARIANT_COLUMN_NAME,
    SEQUENCE_ALIGNMENT_DONE_COLUMN_NAME,
    STATE_COLUMN_NAME_LIST,
    STATUS_FAILED,
    STATUS_REQUIRED,
    STATUS_SKIPPED,
    STATUS_SUCCESS,
    STATUS_WARNING,
    STEP_STATUS_COLUMN_NAME_LIST,
    UNIPROT_ID_COLUMN_NAME,
    VARIANT_POLICY_COLUMN_NAME,
)

# ---------------------------------------------------------------------------
# XLSX-only derived columns
# ---------------------------------------------------------------------------

FINAL_MODEL_CREATED_COLUMN_NAME = "final_model"
FINAL_MODEL_TYPE_COLUMN_NAME = "final_model_type"
FINAL_MODEL_PATH_COLUMN_NAME = "final_model_path"

PARAMETER_AUDIT_STATUS_COLUMN_NAME = "parameter_audit.status"
PARAMETER_AUDIT_REQUIRES_REPAIR_COLUMN_NAME = "parameter_audit.requires_repair"
PARAMETER_AUDIT_REQUIRES_QM_COLUMN_NAME = "parameter_audit.requires_qm_parameters"
PARAMETER_AUDIT_REQUIRES_METAL_COLUMN_NAME = "parameter_audit.requires_metal_parameters"
PARAMETER_AUDIT_JSON_PATH_COLUMN_NAME = "parameter_audit.json_path"
PARAMETER_AUDIT_LOG_PATH_COLUMN_NAME = "parameter_audit.log_path"

METALS_CHECK_STATUS_COLUMN_NAME = "metals_check.status"
METALS_PARAMETER_REFERENCE_COLUMN_NAME = "metals.parameter_reference"
METALS_GEOMETRY_FOUND_COLUMN_NAME = "metals.geometry_found"
METALS_GEOMETRY_PROBABLE_COLUMN_NAME = "metals.geometry_probable"
METALS_GEOMETRY_MATCH_COLUMN_NAME = "metals.geometry_match"
METALS_CHECK_LOG_PATH_COLUMN_NAME = "metals.check_log_path"
METALS_CHECK_MANIFEST_PATH_COLUMN_NAME = "metals.check_manifest_path"

DERIVED_COLUMN_NAME_LIST = [
    FINAL_MODEL_CREATED_COLUMN_NAME,
    FINAL_MODEL_TYPE_COLUMN_NAME,
    FINAL_MODEL_PATH_COLUMN_NAME,
]

OPTIONAL_KNOWN_EXTRA_COLUMN_NAME_LIST = [
    PARAMETER_AUDIT_STATUS_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_REPAIR_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_QM_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_METAL_COLUMN_NAME,
    PARAMETER_AUDIT_JSON_PATH_COLUMN_NAME,
    PARAMETER_AUDIT_LOG_PATH_COLUMN_NAME,
    METALS_CHECK_STATUS_COLUMN_NAME,
    METALS_PARAMETER_REFERENCE_COLUMN_NAME,
    METALS_GEOMETRY_FOUND_COLUMN_NAME,
    METALS_GEOMETRY_PROBABLE_COLUMN_NAME,
    METALS_GEOMETRY_MATCH_COLUMN_NAME,
    METALS_CHECK_LOG_PATH_COLUMN_NAME,
    METALS_CHECK_MANIFEST_PATH_COLUMN_NAME,
]

LOGO_FILENAME_CANDIDATE_LIST = [
    "logo_xlsx.png",
    "logo.png",
    "fruton_logo.png",
    "FRUTON_logo.png",
]

LOGO_OFFSET_X_IN = 0.04
LOGO_OFFSET_Y_IN = 0.00
LOGO_WIDTH_IN = 0.75
LOGO_HEIGHT_IN = 0.80

# ---------------------------------------------------------------------------
# Palette and style constants
# ---------------------------------------------------------------------------

FONT_NAME = "Liberation Sans"
FONT_SIZE = 10
HEADER_FONT_SIZE = 10
TITLE_FONT_SIZE = 14

NAVY_HEX = "2F3761"
GOLD_HEX = "8A730F"
SOFT_NAVY_HEX = "D5D7DF"
RED_HEX = "C00000"
WHITE_HEX = "FFFFFF"

GREEN_HEX = "70AD47"
SOFT_GREEN_HEX = "D9EAD3"
SOFT_GOLD_HEX = "C5B987"
SOFT_RED_HEX = "F4CCCC"
ORANGE_HEX = "F4B183"
GREY_HEX = "E7E6E6"
STRIPE_HEX = "E4E6ED"
GRID_HEX = "B7B7B7"
LIGHT_GRID_HEX = "D9D9D9"

TITLE_FILL = PatternFill(start_color=NAVY_HEX, end_color=NAVY_HEX, fill_type="solid")
HEADER_FILL = PatternFill(start_color=NAVY_HEX, end_color=NAVY_HEX, fill_type="solid")
KPI_LABEL_FILL = PatternFill(start_color=SOFT_NAVY_HEX, end_color=SOFT_NAVY_HEX, fill_type="solid")
KPI_VALUE_FILL = PatternFill(start_color=WHITE_HEX, end_color=WHITE_HEX, fill_type="solid")
BODY_FILL = PatternFill(start_color=SOFT_NAVY_HEX, end_color=SOFT_NAVY_HEX, fill_type="solid")
ROW_STRIPE_FILL = PatternFill(start_color=STRIPE_HEX, end_color=STRIPE_HEX, fill_type="solid")

FINAL_YES_FILL = PatternFill(start_color=WHITE_HEX, end_color=WHITE_HEX, fill_type="solid")
FINAL_NO_FILL = PatternFill(start_color=RED_HEX, end_color=RED_HEX, fill_type="solid")
SUCCESS_FILL = PatternFill(start_color="E8E3CF", end_color="E8E3CF", fill_type="solid")
REVIEW_FILL = PatternFill(start_color=SOFT_GOLD_HEX, end_color=SOFT_GOLD_HEX, fill_type="solid")
STRONG_REVIEW_FILL = PatternFill(start_color=GOLD_HEX, end_color=GOLD_HEX, fill_type="solid")
FAIL_FILL = PatternFill(start_color=SOFT_RED_HEX, end_color=SOFT_RED_HEX, fill_type="solid")
SOFT_NAVY_FILL = PatternFill(start_color=SOFT_NAVY_HEX, end_color=SOFT_NAVY_HEX, fill_type="solid")
SKIP_FILL = PatternFill(start_color=SOFT_NAVY_HEX, end_color=SOFT_NAVY_HEX, fill_type="solid")
NEUTRAL_FILL = PatternFill(start_color=GREY_HEX, end_color=GREY_HEX, fill_type="solid")
ORANGE_FILL = PatternFill(start_color=ORANGE_HEX, end_color=ORANGE_HEX, fill_type="solid")

MODEL_GROUP_FILL = PatternFill(start_color="F4F6FB", end_color="F4F6FB", fill_type="solid")
CHEMISTRY_GROUP_FILL = PatternFill(start_color="FBF8EA", end_color="FBF8EA", fill_type="solid")
GAP_GROUP_FILL = PatternFill(start_color="FBF8EA", end_color="FBF8EA", fill_type="solid")
STATUS_GROUP_FILL = PatternFill(start_color="F0F2F7", end_color="F0F2F7", fill_type="solid")

TITLE_FONT = Font(name=FONT_NAME, size=TITLE_FONT_SIZE, bold=True, color=WHITE_HEX)
HEADER_FONT = Font(name=FONT_NAME, size=HEADER_FONT_SIZE, bold=True, color=WHITE_HEX)
KPI_LABEL_FONT = Font(name=FONT_NAME, size=FONT_SIZE, bold=True, color=NAVY_HEX)
KPI_VALUE_FONT = Font(name=FONT_NAME, size=FONT_SIZE, bold=True, color="111827")
PDB_FONT = Font(name=FONT_NAME, size=FONT_SIZE, bold=True, color=NAVY_HEX)
PDB_MISSING_FONT = Font(name=FONT_NAME, size=FONT_SIZE, bold=True, color=RED_HEX)
FINAL_MODEL_YES_FONT = Font(name=FONT_NAME, size=FONT_SIZE, bold=True, color=NAVY_HEX)
DATA_FONT = Font(name=FONT_NAME, size=FONT_SIZE, color="111827")
MUTED_FONT = Font(name=FONT_NAME, size=FONT_SIZE, color="666666")
WHITE_BOLD_FONT = Font(name=FONT_NAME, size=FONT_SIZE, bold=True, color=WHITE_HEX)
LINK_FONT = Font(name=FONT_NAME, size=FONT_SIZE, color=NAVY_HEX, underline="single")

TITLE_ALIGNMENT = Alignment(horizontal="left", vertical="center")
HEADER_ALIGNMENT = Alignment(horizontal="center", vertical="center", wrap_text=True)
DATA_ALIGNMENT = Alignment(vertical="top", wrap_text=True)
CENTER_ALIGNMENT = Alignment(horizontal="center", vertical="center", wrap_text=True)

GRID_SIDE = Side(style="thin", color=GRID_HEX)
LIGHT_GRID_SIDE = Side(style="thin", color=LIGHT_GRID_HEX)
NAVY_SIDE = Side(style="thin", color=NAVY_HEX)
RED_SIDE = Side(style="medium", color=RED_HEX)

GRID_BORDER = Border(
    left=GRID_SIDE,
    right=GRID_SIDE,
    top=LIGHT_GRID_SIDE,
    bottom=LIGHT_GRID_SIDE,
)

HEADER_BORDER = Border(
    left=NAVY_SIDE,
    right=NAVY_SIDE,
    top=NAVY_SIDE,
    bottom=NAVY_SIDE,
)

MISSING_ROW_BORDER = Border(
    left=RED_SIDE,
    right=RED_SIDE,
    top=RED_SIDE,
    bottom=RED_SIDE,
)

# ---------------------------------------------------------------------------
# Column groups
# ---------------------------------------------------------------------------

HYPERLINK_COLUMN_NAME_SET = {
    PDB_DIRECTORY_COLUMN_NAME,
    FASTA_DIRECTORY_COLUMN_NAME,
    ALIGNMENT_DIRECTORY_COLUMN_NAME,
    COMPONENTS_DIRECTORY_COLUMN_NAME,
    FILLER_DIRECTORY_COLUMN_NAME,
    PREPARED_DIRECTORY_COLUMN_NAME,
    METALL_PARAMS_DIRECTORY_COLUMN_NAME,
    FILLER_MODEL_PATH_COLUMN_NAME,
    PROTONATION_INPUT_PATH_COLUMN_NAME,
    PROTONATION_OUTPUT_PATH_COLUMN_NAME,
    INTERNAL_CAPPING_INPUT_PATH_COLUMN_NAME,
    INTERNAL_CAPPING_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_PROTEIN_INPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_GAPS_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_MODELLER_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_ALPHAFOLD_OUTPUT_PATH_COLUMN_NAME,
    METALL_PARAMS_SITE_COUNT_COLUMN_NAME,
    METALL_PARAMS_MANIFEST_PATH_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_MANIFEST_PATH_COLUMN_NAME,
    FINAL_MODEL_PATH_COLUMN_NAME,
    PARAMETER_AUDIT_JSON_PATH_COLUMN_NAME,
    PARAMETER_AUDIT_LOG_PATH_COLUMN_NAME,
    METALS_CHECK_LOG_PATH_COLUMN_NAME,
    METALS_CHECK_MANIFEST_PATH_COLUMN_NAME,
}

STATUS_COLOR_COLUMN_NAME_SET = set(STEP_STATUS_COLUMN_NAME_LIST) | {
    PARAMETER_AUDIT_STATUS_COLUMN_NAME,
    METALS_CHECK_STATUS_COLUMN_NAME,
}

SEMANTIC_COLOR_COLUMN_NAME_SET = {
    FINAL_MODEL_CREATED_COLUMN_NAME,
    HAS_METALS_COLUMN_NAME,
    HAS_LIGANDS_COLUMN_NAME,
    HAS_NONSTANDARD_RESIDUES_COLUMN_NAME,
    HAS_GAPS_COLUMN_NAME,
    RETAIN_GAPS_VARIANT_COLUMN_NAME,
    RETAIN_MODELLER_VARIANT_COLUMN_NAME,
    RETAIN_ALPHAFOLD_VARIANT_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_REPAIR_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_QM_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_METAL_COLUMN_NAME,
    METALS_GEOMETRY_MATCH_COLUMN_NAME,
}

MODEL_GROUP_COLUMN_NAME_SET = {
    FINAL_MODEL_TYPE_COLUMN_NAME,
    AVAILABLE_MODELS_COLUMN_NAME,
}

CHEMISTRY_GROUP_COLUMN_NAME_SET = {
    HAS_METALS_COLUMN_NAME,
    HAS_NONSTANDARD_RESIDUES_COLUMN_NAME,
    HAS_LIGANDS_COLUMN_NAME,
    METALS_PARAMETER_REFERENCE_COLUMN_NAME,
    METALS_GEOMETRY_FOUND_COLUMN_NAME,
    METALS_GEOMETRY_PROBABLE_COLUMN_NAME,
    METALS_GEOMETRY_MATCH_COLUMN_NAME,
}

GAP_GROUP_COLUMN_NAME_SET = {
    HAS_GAPS_COLUMN_NAME,
    N_GAPS_COLUMN_NAME,
    GAP_SIZES_COLUMN_NAME,
}

STATUS_GROUP_COLUMN_NAME_SET = {
    FILLER_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_VARIANT_COLUMN_NAME,
}

OVERVIEW_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    UNIPROT_ID_COLUMN_NAME,
    RANGE_COLUMN_NAME,
    FINAL_MODEL_CREATED_COLUMN_NAME,
    FINAL_MODEL_TYPE_COLUMN_NAME,
    AVAILABLE_MODELS_COLUMN_NAME,
    HAS_METALS_COLUMN_NAME,
    METALL_PARAMS_STATUS_COLUMN_NAME,
    HAS_NONSTANDARD_RESIDUES_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_STATUS_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_N_RESIDUES_COLUMN_NAME,
    HAS_LIGANDS_COLUMN_NAME,
    HAS_GAPS_COLUMN_NAME,
    N_GAPS_COLUMN_NAME,
    GAP_SIZES_COLUMN_NAME,
    PARAMETER_AUDIT_STATUS_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_QM_COLUMN_NAME,
    FILLER_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_VARIANT_COLUMN_NAME,
    PREPARED_STRUCTURE_ACTUAL_RANGE_COLUMN_NAME,
]

PREPARATION_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    PDB_SYNC_DONE_COLUMN_NAME,
    FASTA_FILES_DONE_COLUMN_NAME,
    SEQUENCE_ALIGNMENT_DONE_COLUMN_NAME,
    INSERTION_CODES_DONE_COLUMN_NAME,
    PARAMETER_AUDIT_STATUS_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_REPAIR_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_QM_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_METAL_COLUMN_NAME,
    FILLER_STATUS_COLUMN_NAME,
    FILLER_MODEL_SOURCE_COLUMN_NAME,
]

COMPONENTS_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    HAS_METALS_COLUMN_NAME,
    METALS_CHECK_STATUS_COLUMN_NAME,
    METALS_ION_TYPE_COLUMN_NAME,
    METALS_CLASS_COLUMN_NAME,
    METALS_MODEL_READY_COLUMN_NAME,
    METALS_PARAMETER_REFERENCE_COLUMN_NAME,
    HAS_LIGANDS_COLUMN_NAME,
    HAS_NONSTANDARD_RESIDUES_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_STATUS_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_N_RESIDUES_COLUMN_NAME,
]

GAPS_AND_VARIANTS_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    N_GAPS_COLUMN_NAME,
    GAP_SIZES_COLUMN_NAME,
    HAS_GAPS_COLUMN_NAME,
    FILLER_STATUS_COLUMN_NAME,
    FILLER_MODEL_SOURCE_COLUMN_NAME,
    VARIANT_POLICY_COLUMN_NAME,
    RETAIN_GAPS_VARIANT_COLUMN_NAME,
    RETAIN_MODELLER_VARIANT_COLUMN_NAME,
    RETAIN_ALPHAFOLD_VARIANT_COLUMN_NAME,
    PREPARED_STRUCTURE_VARIANT_COLUMN_NAME,
    AVAILABLE_MODELS_COLUMN_NAME,
]

CHEMISTRY_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    PROTONATION_STATUS_COLUMN_NAME,
    PROTONATION_INPUT_SOURCE_COLUMN_NAME,
    INTERNAL_CAPPING_STATUS_COLUMN_NAME,
    METALS_CHECK_STATUS_COLUMN_NAME,
    METALS_ION_TYPE_COLUMN_NAME,
    METALS_CLASS_COLUMN_NAME,
    METALS_MODEL_READY_COLUMN_NAME,
    METALS_PARAMETER_REFERENCE_COLUMN_NAME,
    METALS_GEOMETRY_FOUND_COLUMN_NAME,
    METALS_GEOMETRY_PROBABLE_COLUMN_NAME,
    METALS_GEOMETRY_MATCH_COLUMN_NAME,
    METALL_PARAMS_STATUS_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_STATUS_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_N_RESIDUES_COLUMN_NAME,
    PARAMETER_AUDIT_STATUS_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_REPAIR_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_QM_COLUMN_NAME,
    PARAMETER_AUDIT_REQUIRES_METAL_COLUMN_NAME,
]

PREPARED_OUTPUTS_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    FINAL_MODEL_CREATED_COLUMN_NAME,
    FINAL_MODEL_TYPE_COLUMN_NAME,
    AVAILABLE_MODELS_COLUMN_NAME,
    METALS_MODEL_READY_COLUMN_NAME,
    METALS_CHECK_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_STATUS_COLUMN_NAME,
    PREPARED_STRUCTURE_VARIANT_COLUMN_NAME,
    FINAL_MODEL_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_GAPS_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_MODELLER_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_ALPHAFOLD_OUTPUT_PATH_COLUMN_NAME,
]

PATHS_COLUMN_NAME_LIST = [
    PDB_ID_COLUMN_NAME,
    PDB_DIRECTORY_COLUMN_NAME,
    COMPONENTS_DIRECTORY_COLUMN_NAME,
    ALIGNMENT_DIRECTORY_COLUMN_NAME,
    FILLER_DIRECTORY_COLUMN_NAME,
    PREPARED_DIRECTORY_COLUMN_NAME,
    FINAL_MODEL_PATH_COLUMN_NAME,
    FILLER_MODEL_PATH_COLUMN_NAME,
    PARAMETER_AUDIT_JSON_PATH_COLUMN_NAME,
    PARAMETER_AUDIT_LOG_PATH_COLUMN_NAME,
    METALS_CHECK_LOG_PATH_COLUMN_NAME,
    METALS_CHECK_MANIFEST_PATH_COLUMN_NAME,
    NONSTD_RESIDUE_PARAMS_MANIFEST_PATH_COLUMN_NAME,
    PROTONATION_INPUT_PATH_COLUMN_NAME,
    PROTONATION_OUTPUT_PATH_COLUMN_NAME,
    INTERNAL_CAPPING_INPUT_PATH_COLUMN_NAME,
    INTERNAL_CAPPING_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_PROTEIN_INPUT_PATH_COLUMN_NAME,
    PREPARED_STRUCTURE_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_GAPS_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_MODELLER_OUTPUT_PATH_COLUMN_NAME,
    PREPARED_ALPHAFOLD_OUTPUT_PATH_COLUMN_NAME,
]

WORKSHEET_LAYOUTS: list[tuple[str, list[str]]] = [
    ("overview", OVERVIEW_COLUMN_NAME_LIST),
    ("preparation", PREPARATION_COLUMN_NAME_LIST),
    ("components", COMPONENTS_COLUMN_NAME_LIST),
    ("gaps_and_variants", GAPS_AND_VARIANTS_COLUMN_NAME_LIST),
    ("chemistry", CHEMISTRY_COLUMN_NAME_LIST),
    ("prepared_outputs", PREPARED_OUTPUTS_COLUMN_NAME_LIST),
    ("paths", PATHS_COLUMN_NAME_LIST),
    ("full_state", []),
]
