"""Metal classification and geometry checks for FRUTON prepared models.

The module inspects metal atoms in starting structures, component files,
produced FRUTON models, and prepared variants before the final workbook is written. It keeps the policy small:
standard non-transition alkali/alkaline-earth ions are treated as standard-ion
parameter cases, while transition metals are analysed geometrically and flagged
for the metal-parameter branch. Crystal waters are included in the analysis PDB
because crystallographic water molecules frequently complete metal coordination
shells and must not be ignored when deciding the local geometry.

ChimeraX support is deliberately optional. When a ChimeraX executable is found,
this module writes and runs a small contacts script so the contact analysis can
be inspected with the same external tool that a user would use manually. The
structured TSV/JSON output is still generated by deterministic Python distance
analysis, so the pipeline remains usable on machines where ChimeraX is not
installed.
"""

from __future__ import annotations

import itertools
import json
import math
import shutil
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

MetalCheckStatus = Literal["success", "warning", "required", "failed", "skipped"]
MetalClass = Literal[
    "none",
    "standard_nontransition",
    "transition",
    "mixed",
    "unsupported_nontransition",
]

WATER_RESIDUE_NAMES = {"HOH", "WAT", "H2O", "SOL", "TIP3", "TIP3P"}
DONOR_ELEMENTS = {"N", "O", "S", "SE"}

TRANSITION_METAL_ELEMENTS = {
    "SC",
    "TI",
    "V",
    "CR",
    "MN",
    "FE",
    "CO",
    "NI",
    "CU",
    "ZN",
    "Y",
    "ZR",
    "NB",
    "MO",
    "TC",
    "RU",
    "RH",
    "PD",
    "AG",
    "CD",
    "HF",
    "TA",
    "W",
    "RE",
    "OS",
    "IR",
    "PT",
    "AU",
    "HG",
}

METAL_ELEMENTS = TRANSITION_METAL_ELEMENTS | {
    "LI",
    "NA",
    "K",
    "RB",
    "CS",
    "MG",
    "CA",
    "SR",
    "BA",
    "AL",
}

# Legacy PDB files rarely carry a reliable charge for metal atoms. When a charge
# exists it sits in atom columns 79-80, but many PDB files leave it blank. For
# common elemental ion CCD residue names we therefore use a conservative local
# mapping that mirrors the usual wwPDB/RCSB chemical component identity, e.g.
# FE = Fe(III) and FE2 = Fe(II). Unknown oxidation states are left explicit
# rather than guessed from coordination geometry.
METAL_RESIDUE_IDENTITY = {
    "LI": ("LI", 1),
    "NA": ("NA", 1),
    "K": ("K", 1),
    "RB": ("RB", 1),
    "CS": ("CS", 1),
    "MG": ("MG", 2),
    "CA": ("CA", 2),
    "SR": ("SR", 2),
    "BA": ("BA", 2),
    "AL": ("AL", 3),
    "ZN": ("ZN", 2),
    "FE": ("FE", 3),
    "FE2": ("FE", 2),
    "MN": ("MN", 2),
    "CU": ("CU", 2),
    "CU1": ("CU", 1),
    "CO": ("CO", 2),
    "NI": ("NI", 2),
    "CD": ("CD", 2),
    "HG": ("HG", 2),
}

STANDARD_NONTRANSITION_IONS = {
    "LI": {
        "ion_label": "Li+",
        "charge": 1,
        "parameter_reference": "Joung-Cheatham monovalent ion parameters; verify water-model-specific frcmod, e.g. ionsjc_tip3p for TIP3P.",
    },
    "NA": {
        "ion_label": "Na+",
        "charge": 1,
        "parameter_reference": "Joung-Cheatham monovalent ion parameters; verify water-model-specific frcmod, e.g. ionsjc_tip3p for TIP3P.",
    },
    "K": {
        "ion_label": "K+",
        "charge": 1,
        "parameter_reference": "Joung-Cheatham monovalent ion parameters; verify water-model-specific frcmod, e.g. ionsjc_tip3p for TIP3P.",
    },
    "RB": {
        "ion_label": "Rb+",
        "charge": 1,
        "parameter_reference": "Joung-Cheatham monovalent ion parameters; verify water-model-specific frcmod, e.g. ionsjc_tip3p for TIP3P.",
    },
    "CS": {
        "ion_label": "Cs+",
        "charge": 1,
        "parameter_reference": "Joung-Cheatham monovalent ion parameters; verify water-model-specific frcmod, e.g. ionsjc_tip3p for TIP3P.",
    },
    "MG": {
        "ion_label": "Mg2+",
        "charge": 2,
        "parameter_reference": "Standard AMBER divalent-ion route; not a Joung-Cheatham monovalent ion. Verify selected Mg2+ parameters against the water model.",
    },
    "CA": {
        "ion_label": "Ca2+",
        "charge": 2,
        "parameter_reference": "Standard AMBER divalent-ion route; not a Joung-Cheatham monovalent ion. Verify selected Ca2+ parameters against the water model.",
    },
    "SR": {
        "ion_label": "Sr2+",
        "charge": 2,
        "parameter_reference": "Standard divalent-ion route; verify selected Sr2+ parameters against the water model.",
    },
    "BA": {
        "ion_label": "Ba2+",
        "charge": 2,
        "parameter_reference": "Standard divalent-ion route; verify selected Ba2+ parameters against the water model.",
    },
    "AL": {
        "ion_label": "Al3+",
        "charge": 3,
        "parameter_reference": "Standard trivalent non-transition ion route; verify selected Al3+ parameters against the force field and water model.",
    },
}

TRANSITION_ION_GEOMETRY_PREFERENCES = {
    "ZN": ["tetrahedral", "trigonal_bipyramidal", "octahedral"],
    "CU": ["square_planar", "square_pyramidal", "octahedral"],
    "FE": ["octahedral", "tetrahedral"],
    "MN": ["octahedral"],
    "CO": ["octahedral", "tetrahedral"],
    "NI": ["octahedral", "square_planar"],
    "CR": ["octahedral"],
    "V": ["octahedral", "tetrahedral"],
    "MO": ["octahedral"],
    "W": ["octahedral"],
    "CD": ["tetrahedral", "octahedral"],
    "HG": ["linear", "tetrahedral"],
}


@dataclass(frozen=True)
class PDBAtomRecord:
    """Minimal PDB atom record used for metal-contact analysis."""

    serial: int
    record_name: str
    atom_name: str
    residue_name: str
    chain_id: str
    residue_number: int
    insertion_code: str
    element: str
    formal_charge: int | None
    x: float
    y: float
    z: float
    source_path: str
    source_role: str
    raw_line: str

    @property
    def residue_label(self) -> str:
        insertion = self.insertion_code.strip()
        return f"{self.residue_name} {self.chain_id or '<blank>'} {self.residue_number}{insertion}"

    @property
    def atom_label(self) -> str:
        return f"{self.residue_label} {self.atom_name.strip()}"


@dataclass(frozen=True)
class MetalContact:
    """One donor atom close enough to be treated as a metal contact."""

    metal_label: str
    metal_element: str
    donor_label: str
    donor_element: str
    donor_residue_name: str
    donor_chain_id: str
    donor_residue_number: int
    donor_atom_name: str
    distance_angstrom: float
    donor_source_role: str
    vector_x: float
    vector_y: float
    vector_z: float


@dataclass(frozen=True)
class MetalSiteSummary:
    """Classification summary for one metal atom in one model."""

    metal_label: str
    element: str
    ion_label: str
    metal_class: MetalClass
    coordination_number: int
    found_geometry: str
    probable_geometry: str
    geometry_match: str
    parameter_reference: str
    requires_transition_parameters: bool
    contacts: tuple[MetalContact, ...]


@dataclass(frozen=True)
class MetalCheckResult:
    """Full metal-check result for one PDB model or prepared variant."""

    pdb_id: str
    variant_label: str
    input_model_path: Path
    analysis_input_path: Path
    contacts_tsv_path: Path
    manifest_path: Path
    log_path: Path
    chimera_script_path: Path | None
    chimera_log_path: Path | None
    chimera_status: str
    status: MetalCheckStatus
    metal_class: MetalClass
    ion_type_text: str
    parameter_reference_text: str
    found_geometry_text: str
    probable_geometry_text: str
    geometry_match: str
    model_metal_ready: bool
    site_summaries: tuple[MetalSiteSummary, ...]
    message: str


def run_metals_check_for_model(
    *,
    pdb_id: str,
    protein_dir: str | Path,
    variant_label: str,
    model_pdb_path: str | Path,
    metals_pdb_path: str | Path | None = None,
    water_pdb_path: str | Path | None = None,
    output_dir: str | Path | None = None,
    reference_json_path: str | Path | None = None,
    chimera_executable: str | None = None,
    use_chimera: bool = True,
    contact_cutoff_angstrom: float = 3.5,
) -> MetalCheckResult:
    """Classify model metals and write contact/geometry audit artefacts.

    ``model_pdb_path`` should be a produced model or prepared variant, not the raw
    starting PDB. If crystal-water and metal component files are supplied, they
    are appended to the analysis copy when they are not already present. This
    ensures transition-metal coordination analysis sees water donors that may
    complete the coordination shell.
    """

    protein_dir = Path(protein_dir).resolve()
    model_path = Path(model_pdb_path).resolve()
    safe_variant = _safe_token(variant_label)
    resolved_output_dir = (
        Path(output_dir).resolve()
        if output_dir is not None
        else protein_dir / "components" / "metals_check" / safe_variant
    )
    resolved_output_dir.mkdir(parents=True, exist_ok=True)

    analysis_input_path = resolved_output_dir / f"{pdb_id}_{safe_variant}_metal_analysis_input.pdb"
    contacts_tsv_path = resolved_output_dir / f"{pdb_id}_{safe_variant}_metal_contacts.tsv"
    manifest_path = resolved_output_dir / f"{pdb_id}_{safe_variant}_metal_check.json"
    log_path = protein_dir.parent / "logs" / pdb_id / f"metalls_check_{safe_variant}.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    water_path = Path(water_pdb_path).resolve() if water_pdb_path is not None else None
    metals_path = Path(metals_pdb_path).resolve() if metals_pdb_path is not None else None

    _write_analysis_pdb(
        model_pdb_path=model_path,
        output_pdb_path=analysis_input_path,
        water_pdb_path=water_path,
        metals_pdb_path=metals_path,
    )

    atom_records = read_pdb_atom_records(analysis_input_path, source_role="analysis")
    metal_atoms = [atom for atom in atom_records if is_true_metal_atom(atom)]

    chimera_script_path: Path | None = None
    chimera_log_path: Path | None = None
    chimera_status = "skipped"
    if use_chimera and metal_atoms:
        chimera_result = _run_chimera_contact_script(
            analysis_input_path=analysis_input_path,
            output_dir=resolved_output_dir,
            pdb_id=pdb_id,
            variant_label=safe_variant,
            chimera_executable=chimera_executable,
            contact_cutoff_angstrom=contact_cutoff_angstrom,
        )
        chimera_script_path = chimera_result["script_path"]
        chimera_log_path = chimera_result["log_path"]
        chimera_status = chimera_result["status"]

    if not metal_atoms:
        result = MetalCheckResult(
            pdb_id=pdb_id,
            variant_label=variant_label,
            input_model_path=model_path,
            analysis_input_path=analysis_input_path,
            contacts_tsv_path=contacts_tsv_path,
            manifest_path=manifest_path,
            log_path=log_path,
            chimera_script_path=chimera_script_path,
            chimera_log_path=chimera_log_path,
            chimera_status=chimera_status,
            status="skipped",
            metal_class="none",
            ion_type_text="none",
            parameter_reference_text="none",
            found_geometry_text="none",
            probable_geometry_text="none",
            geometry_match="n/a",
            model_metal_ready=True,
            site_summaries=(),
            message="No metal atoms detected in prepared model.",
        )
        _write_contacts_tsv(contacts_tsv_path, ())
        _write_result_files(result)
        return result

    site_summaries = tuple(
        summarize_metal_site(
            metal_atom=metal_atom,
            atom_records=atom_records,
            contact_cutoff_angstrom=contact_cutoff_angstrom,
        )
        for metal_atom in metal_atoms
    )

    all_classes = {site.metal_class for site in site_summaries}
    if all_classes == {"standard_nontransition"}:
        status: MetalCheckStatus = "success"
        metal_class: MetalClass = "standard_nontransition"
        model_metal_ready = True
        message = "Only supported standard non-transition ions detected."
    elif any(site.metal_class == "transition" for site in site_summaries):
        status = "required"
        metal_class = "mixed" if len(all_classes) > 1 else "transition"
        model_metal_ready = False
        message = "Transition-metal site detected; geometry recorded for metal-parameter branch."
    else:
        status = "required"
        metal_class = "unsupported_nontransition"
        model_metal_ready = False
        message = "Unsupported non-transition metal detected; explicit parameters are required."

    geometry_matches = [site.geometry_match for site in site_summaries if site.metal_class == "transition"]
    if geometry_matches:
        geometry_match = "yes" if all(value == "yes" for value in geometry_matches) else "no"
    else:
        geometry_match = "n/a"

    result = MetalCheckResult(
        pdb_id=pdb_id,
        variant_label=variant_label,
        input_model_path=model_path,
        analysis_input_path=analysis_input_path,
        contacts_tsv_path=contacts_tsv_path,
        manifest_path=manifest_path,
        log_path=log_path,
        chimera_script_path=chimera_script_path,
        chimera_log_path=chimera_log_path,
        chimera_status=chimera_status,
        status=status,
        metal_class=metal_class,
        ion_type_text="; ".join(site.ion_label for site in site_summaries),
        parameter_reference_text="; ".join(_unique_keep_order(site.parameter_reference for site in site_summaries)),
        found_geometry_text="; ".join(site.found_geometry for site in site_summaries),
        probable_geometry_text="; ".join(site.probable_geometry for site in site_summaries),
        geometry_match=geometry_match,
        model_metal_ready=model_metal_ready,
        site_summaries=site_summaries,
        message=message,
    )

    all_contacts: list[MetalContact] = []
    for site in site_summaries:
        all_contacts.extend(site.contacts)
    _write_contacts_tsv(contacts_tsv_path, all_contacts)
    _write_result_files(result)
    return result


def run_metals_inventory_for_structure(
    *,
    pdb_id: str,
    protein_dir: str | Path,
    model_pdb_path: str | Path,
    metals_pdb_path: str | Path | None = None,
    water_pdb_path: str | Path | None = None,
    output_dir: str | Path | None = None,
    reference_json_path: str | Path | None = None,
    use_chimera: bool = False,
) -> MetalCheckResult:
    """Run the same metal check as an input inventory.

    This wrapper is intentionally thin. It exists so FRUTON can record metal
    identity and parameter policy immediately after component splitting, even if
    no prepared variant is eventually produced. The check still includes crystal
    waters and separated metal component files when they are available.
    """

    return run_metals_check_for_model(
        pdb_id=pdb_id,
        protein_dir=protein_dir,
        variant_label="input_inventory",
        model_pdb_path=model_pdb_path,
        metals_pdb_path=metals_pdb_path,
        water_pdb_path=water_pdb_path,
        output_dir=output_dir,
        reference_json_path=reference_json_path,
        use_chimera=use_chimera,
    )


def summarize_metal_site(
    *,
    metal_atom: PDBAtomRecord,
    atom_records: list[PDBAtomRecord],
    contact_cutoff_angstrom: float,
) -> MetalSiteSummary:
    """Classify one metal atom and its coordination shell."""

    contacts = tuple(
        sorted(
            find_metal_contacts(
                metal_atom=metal_atom,
                atom_records=atom_records,
                contact_cutoff_angstrom=contact_cutoff_angstrom,
            ),
            key=lambda contact: contact.distance_angstrom,
        )
    )

    if metal_atom.element in STANDARD_NONTRANSITION_IONS:
        ion_info = STANDARD_NONTRANSITION_IONS[metal_atom.element]
        return MetalSiteSummary(
            metal_label=metal_atom.atom_label,
            element=metal_atom.element,
            ion_label=_ion_label_from_atom(metal_atom, default=str(ion_info["ion_label"])),
            metal_class="standard_nontransition",
            coordination_number=len(contacts),
            found_geometry="not_required_for_standard_ion",
            probable_geometry="not_required_for_standard_ion",
            geometry_match="n/a",
            parameter_reference=str(ion_info["parameter_reference"]),
            requires_transition_parameters=False,
            contacts=contacts,
        )

    if metal_atom.element in TRANSITION_METAL_ELEMENTS:
        found_geometry = classify_coordination_geometry(
            metal_atom=metal_atom,
            contacts=contacts,
        )
        probable_geometry_list = TRANSITION_ION_GEOMETRY_PREFERENCES.get(
            metal_atom.element,
            ["unknown"],
        )
        probable_geometry = "|".join(probable_geometry_list)
        geometry_match = "yes" if found_geometry in probable_geometry_list else "no"
        return MetalSiteSummary(
            metal_label=metal_atom.atom_label,
            element=metal_atom.element,
            ion_label=_transition_ion_label(metal_atom),
            metal_class="transition",
            coordination_number=len(contacts),
            found_geometry=found_geometry,
            probable_geometry=probable_geometry,
            geometry_match=geometry_match,
            parameter_reference="transition-metal parameters required; geometry recorded for Gaussian/RESP/CESGA branch",
            requires_transition_parameters=True,
            contacts=contacts,
        )

    return MetalSiteSummary(
        metal_label=metal_atom.atom_label,
        element=metal_atom.element,
        ion_label=metal_atom.element,
        metal_class="unsupported_nontransition",
        coordination_number=len(contacts),
        found_geometry="unsupported_ion",
        probable_geometry="unsupported_ion",
        geometry_match="n/a",
        parameter_reference="unsupported non-transition metal; explicit parameters required",
        requires_transition_parameters=False,
        contacts=contacts,
    )


def find_metal_contacts(
    *,
    metal_atom: PDBAtomRecord,
    atom_records: list[PDBAtomRecord],
    contact_cutoff_angstrom: float,
) -> list[MetalContact]:
    """Return donor atoms within the coordination cutoff around one metal."""

    contacts: list[MetalContact] = []
    for atom in atom_records:
        if atom is metal_atom:
            continue
        if is_true_metal_atom(atom):
            continue
        if atom.element not in DONOR_ELEMENTS:
            continue
        distance = distance_between_atoms(metal_atom, atom)
        if distance > contact_cutoff_angstrom:
            continue
        contacts.append(
            MetalContact(
                metal_label=metal_atom.atom_label,
                metal_element=metal_atom.element,
                donor_label=atom.atom_label,
                donor_element=atom.element,
                donor_residue_name=atom.residue_name,
                donor_chain_id=atom.chain_id,
                donor_residue_number=atom.residue_number,
                donor_atom_name=atom.atom_name,
                distance_angstrom=round(distance, 3),
                donor_source_role=atom.source_role,
                vector_x=atom.x - metal_atom.x,
                vector_y=atom.y - metal_atom.y,
                vector_z=atom.z - metal_atom.z,
            )
        )
    return contacts


def classify_coordination_geometry(
    *,
    metal_atom: PDBAtomRecord,
    contacts: tuple[MetalContact, ...],
) -> str:
    """Classify a transition-metal site with conservative geometric heuristics."""

    coordination_number = len(contacts)
    if coordination_number == 0:
        return "uncoordinated"
    if coordination_number == 1:
        return "monodentate_contact"
    if coordination_number == 2:
        angle = _angle_for_two_contacts(metal_atom, contacts)
        return "linear" if angle >= 150.0 else "bent"
    if coordination_number == 3:
        return "trigonal_planar"
    if coordination_number == 4:
        if _is_square_planar_like(metal_atom, contacts):
            return "square_planar"
        return "tetrahedral"
    if coordination_number == 5:
        if _has_opposite_contact_pair(metal_atom, contacts, min_angle=155.0):
            return "trigonal_bipyramidal"
        return "square_pyramidal"
    if coordination_number == 6:
        return "octahedral"
    if coordination_number == 7:
        return "pentagonal_bipyramidal_or_capped_octahedral"
    return f"high_coordination_{coordination_number}"


def read_pdb_atom_records(pdb_path: str | Path, *, source_role: str) -> list[PDBAtomRecord]:
    """Read ATOM/HETATM records with Gemmi first and legacy parsing as fallback.

    Gemmi is preferred because it understands the PDB/mmCIF structure hierarchy,
    element objects, heterogen flags, residue identity, and atom coordinates
    without relying on fragile atom-name heuristics. This avoids the common
    legacy-PDB error where protein atom names such as ``HG``, ``CD``, or ``CA``
    are read as Hg, Cd, or Ca. The fallback parser remains available for
    environments where Gemmi is not installed, but the normal FRUTON environment
    should use Gemmi.
    """

    path = Path(pdb_path)

    try:
        return _read_atom_records_with_gemmi(path, source_role=source_role)
    except Exception:
        return _read_atom_records_from_pdb_lines(path, source_role=source_role)


def _read_atom_records_with_gemmi(pdb_path: Path, *, source_role: str) -> list[PDBAtomRecord]:
    """Read atom records through Gemmi while preserving FRUTON's flat record type."""

    import gemmi

    structure = gemmi.read_structure(str(pdb_path))
    atom_records: list[PDBAtomRecord] = []

    for model in structure:
        for chain in model:
            for residue in chain:
                record_name = "HETATM" if str(residue.het_flag).upper() == "H" else "ATOM"
                insertion_code = "" if str(residue.seqid.icode).strip() == "?" else str(residue.seqid.icode).strip()

                for atom in residue:
                    element = str(atom.element.name).upper()
                    if element == "D":
                        element = "H"

                    formal_charge = int(atom.charge) if int(atom.charge) != 0 else None
                    if formal_charge is None:
                        formal_charge = _charge_from_residue_name(str(residue.name).strip().upper())

                    atom_records.append(
                        PDBAtomRecord(
                            serial=int(atom.serial) if int(atom.serial) else 0,
                            record_name=record_name,
                            atom_name=str(atom.name).strip(),
                            residue_name=str(residue.name).strip().upper(),
                            chain_id=str(chain.name).strip(),
                            residue_number=int(residue.seqid.num) if residue.seqid.num is not None else 0,
                            insertion_code=insertion_code,
                            element=element,
                            formal_charge=formal_charge,
                            x=float(atom.pos.x),
                            y=float(atom.pos.y),
                            z=float(atom.pos.z),
                            source_path=str(pdb_path),
                            source_role=source_role,
                            raw_line="",
                        )
                    )

    return atom_records


def _read_atom_records_from_pdb_lines(pdb_path: Path, *, source_role: str) -> list[PDBAtomRecord]:
    """Read ATOM/HETATM records from fixed-width PDB lines as a fallback."""

    atom_records: list[PDBAtomRecord] = []
    with pdb_path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\n")
            if not (line.startswith("ATOM  ") or line.startswith("HETATM")):
                continue
            atom_records.append(_parse_pdb_atom_line(line, source_path=pdb_path, source_role=source_role))
    return atom_records


def distance_between_atoms(atom_a: PDBAtomRecord, atom_b: PDBAtomRecord) -> float:
    """Return Euclidean distance between two parsed PDB atom records."""

    dx = atom_a.x - atom_b.x
    dy = atom_a.y - atom_b.y
    dz = atom_a.z - atom_b.z
    return math.sqrt(dx * dx + dy * dy + dz * dz)


def _write_analysis_pdb(
    *,
    model_pdb_path: Path,
    output_pdb_path: Path,
    water_pdb_path: Path | None,
    metals_pdb_path: Path | None,
) -> None:
    """Write analysis PDB with crystal waters and metals available."""

    section_paths = [model_pdb_path]
    if water_pdb_path is not None and water_pdb_path.exists() and not _pdb_contains_water(model_pdb_path):
        section_paths.append(water_pdb_path)
    if metals_pdb_path is not None and metals_pdb_path.exists() and not _pdb_contains_metals(model_pdb_path):
        section_paths.append(metals_pdb_path)

    output_pdb_path.parent.mkdir(parents=True, exist_ok=True)
    atom_serial = 1
    with output_pdb_path.open("w", encoding="utf-8") as output_handle:
        for section_path in section_paths:
            with section_path.open("r", encoding="utf-8", errors="replace") as input_handle:
                for raw_line in input_handle:
                    line = raw_line.rstrip("\n")
                    if line.startswith("ATOM  ") or line.startswith("HETATM"):
                        output_handle.write(f"{line[:6]}{atom_serial:>5}{line[11:]}\n")
                        atom_serial += 1
            output_handle.write("TER\n")
        output_handle.write("END\n")


def _parse_pdb_atom_line(line: str, *, source_path: Path, source_role: str) -> PDBAtomRecord:
    """Parse the subset of a PDB ATOM/HETATM line needed here."""

    atom_name = line[12:16].strip()
    residue_name = line[17:20].strip().upper()
    chain_id = line[21:22].strip()
    insertion_code = line[26:27].strip()
    record_name = line[0:6].strip()
    formal_charge = _parse_pdb_atom_charge(line[78:80] if len(line) >= 80 else "")
    raw_element = line[76:78].strip().upper() if len(line) >= 78 else ""
    element = _infer_element_from_pdb_fields(
        record_name=record_name,
        atom_name=atom_name,
        residue_name=residue_name,
        raw_element=raw_element,
    )
    if formal_charge is None:
        formal_charge = _charge_from_residue_name(residue_name)
    return PDBAtomRecord(
        serial=_safe_int(line[6:11], default=0),
        record_name=record_name,
        atom_name=atom_name,
        residue_name=residue_name,
        chain_id=chain_id,
        residue_number=_safe_int(line[22:26], default=0),
        insertion_code=insertion_code,
        element=element,
        formal_charge=formal_charge,
        x=_safe_float(line[30:38], default=0.0),
        y=_safe_float(line[38:46], default=0.0),
        z=_safe_float(line[46:54], default=0.0),
        source_path=str(source_path),
        source_role=source_role,
        raw_line=line,
    )


def _run_chimera_contact_script(
    *,
    analysis_input_path: Path,
    output_dir: Path,
    pdb_id: str,
    variant_label: str,
    chimera_executable: str | None,
    contact_cutoff_angstrom: float,
) -> dict[str, Path | str | None]:
    """Run a minimal ChimeraX contacts script when ChimeraX is available."""

    executable = chimera_executable or shutil.which("chimerax") or shutil.which("ChimeraX")
    script_path = output_dir / f"{pdb_id}_{variant_label}_chimera_contacts.cxc"
    log_path = output_dir / f"{pdb_id}_{variant_label}_chimera_contacts.log"

    script_text = "\n".join(
        [
            f"open {analysis_input_path}",
            "delete solvent false",
            f"contacts @MN,FE,CO,NI,CU,ZN,CD,HG,CR,V,MO,W restrict @N*,O*,S*,SE* distance {contact_cutoff_angstrom:.2f} reveal true name metal_contacts color gold",
            "save {0}".format(output_dir / f"{pdb_id}_{variant_label}_chimera_session.cxs"),
            "exit",
            "",
        ]
    )
    script_path.write_text(script_text, encoding="utf-8")

    if executable is None:
        log_path.write_text("ChimeraX executable not found; Python contact analysis used.\n", encoding="utf-8")
        return {"script_path": script_path, "log_path": log_path, "status": "missing_executable"}

    try:
        completed = subprocess.run(
            [executable, "--nogui", str(script_path)],
            check=False,
            capture_output=True,
            text=True,
            timeout=180,
        )
    except Exception as error:
        log_path.write_text(f"ChimeraX execution failed: {error!r}\n", encoding="utf-8")
        return {"script_path": script_path, "log_path": log_path, "status": "failed"}

    log_path.write_text(
        completed.stdout + "\n" + completed.stderr,
        encoding="utf-8",
    )
    return {
        "script_path": script_path,
        "log_path": log_path,
        "status": "success" if completed.returncode == 0 else f"returncode_{completed.returncode}",
    }


def _write_contacts_tsv(path: Path, contacts: tuple[MetalContact, ...] | list[MetalContact]) -> None:
    """Write contacts as a compact TSV for manual inspection."""

    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "metal_label",
        "metal_element",
        "donor_label",
        "donor_element",
        "donor_residue_name",
        "donor_chain_id",
        "donor_residue_number",
        "donor_atom_name",
        "distance_angstrom",
        "donor_source_role",
        "vector_x",
        "vector_y",
        "vector_z",
    ]
    with path.open("w", encoding="utf-8") as handle:
        handle.write("\t".join(header) + "\n")
        for contact in contacts:
            handle.write(
                "\t".join(
                    [
                        contact.metal_label,
                        contact.metal_element,
                        contact.donor_label,
                        contact.donor_element,
                        contact.donor_residue_name,
                        contact.donor_chain_id,
                        str(contact.donor_residue_number),
                        contact.donor_atom_name,
                        f"{contact.distance_angstrom:.3f}",
                        contact.donor_source_role,
                        f"{contact.vector_x:.3f}",
                        f"{contact.vector_y:.3f}",
                        f"{contact.vector_z:.3f}",
                    ]
                )
                + "\n"
            )


def _write_result_files(result: MetalCheckResult) -> None:
    """Write JSON manifest and plain-text log for one result."""

    result.manifest_path.parent.mkdir(parents=True, exist_ok=True)
    result.log_path.parent.mkdir(parents=True, exist_ok=True)

    def convert(value):
        if isinstance(value, Path):
            return str(value)
        if isinstance(value, tuple):
            return [convert(item) for item in value]
        if hasattr(value, "__dataclass_fields__"):
            return {key: convert(inner) for key, inner in asdict(value).items()}
        return value

    result.manifest_path.write_text(
        json.dumps(convert(result), indent=2, sort_keys=True),
        encoding="utf-8",
    )

    lines = [
        "metalls_check",
        "============",
        "",
        f"pdb_id                   : {result.pdb_id}",
        f"variant_label            : {result.variant_label}",
        f"input_model_path         : {result.input_model_path}",
        f"analysis_input_path      : {result.analysis_input_path}",
        f"contacts_tsv_path        : {result.contacts_tsv_path}",
        f"manifest_path            : {result.manifest_path}",
        f"chimera_status           : {result.chimera_status}",
        f"status                   : {result.status}",
        f"metal_class              : {result.metal_class}",
        f"ion_type_text            : {result.ion_type_text}",
        f"parameter_reference_text : {result.parameter_reference_text}",
        f"found_geometry_text      : {result.found_geometry_text}",
        f"probable_geometry_text   : {result.probable_geometry_text}",
        f"geometry_match           : {result.geometry_match}",
        f"model_metal_ready        : {result.model_metal_ready}",
        f"message                  : {result.message}",
        "",
        "sites",
        "-----",
    ]
    for site in result.site_summaries:
        lines.extend(
            [
                f"- {site.metal_label}",
                f"  ion_label        : {site.ion_label}",
                f"  metal_class      : {site.metal_class}",
                f"  coordination     : {site.coordination_number}",
                f"  found_geometry   : {site.found_geometry}",
                f"  probable_geometry: {site.probable_geometry}",
                f"  geometry_match   : {site.geometry_match}",
                f"  contacts         : {len(site.contacts)}",
            ]
        )
    result.log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _angle_for_two_contacts(metal_atom: PDBAtomRecord, contacts: tuple[MetalContact, ...]) -> float:
    points = _contact_points_from_labels(metal_atom, contacts)
    if len(points) < 2:
        return 0.0
    return _angle_between_vectors(points[0], points[1])


def _is_square_planar_like(metal_atom: PDBAtomRecord, contacts: tuple[MetalContact, ...]) -> bool:
    points = _contact_points_from_labels(metal_atom, contacts)
    if len(points) != 4:
        return False
    angles = sorted(_angle_between_vectors(a, b) for a, b in itertools.combinations(points, 2))
    near_90 = sum(1 for angle in angles if 70.0 <= angle <= 110.0)
    near_180 = sum(1 for angle in angles if angle >= 150.0)
    return near_90 >= 4 and near_180 >= 1


def _has_opposite_contact_pair(
    metal_atom: PDBAtomRecord,
    contacts: tuple[MetalContact, ...],
    *,
    min_angle: float,
) -> bool:
    points = _contact_points_from_labels(metal_atom, contacts)
    return any(
        _angle_between_vectors(a, b) >= min_angle for a, b in itertools.combinations(points, 2)
    )


def _contact_points_from_labels(
    metal_atom: PDBAtomRecord,
    contacts: tuple[MetalContact, ...],
) -> list[tuple[float, float, float]]:
    """Return donor vectors centered on the metal atom."""

    return [(contact.vector_x, contact.vector_y, contact.vector_z) for contact in contacts]


def _angle_between_vectors(
    vector_a: tuple[float, float, float],
    vector_b: tuple[float, float, float],
) -> float:
    dot = sum(a * b for a, b in zip(vector_a, vector_b, strict=True))
    norm_a = math.sqrt(sum(a * a for a in vector_a))
    norm_b = math.sqrt(sum(b * b for b in vector_b))
    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0
    cosine = max(-1.0, min(1.0, dot / (norm_a * norm_b)))
    return math.degrees(math.acos(cosine))


def _pdb_contains_water(pdb_path: Path) -> bool:
    return any(atom.residue_name in WATER_RESIDUE_NAMES for atom in read_pdb_atom_records(pdb_path, source_role="probe"))


def _pdb_contains_metals(pdb_path: Path) -> bool:
    return any(is_true_metal_atom(atom) for atom in read_pdb_atom_records(pdb_path, source_role="probe"))


def is_true_metal_atom(atom: PDBAtomRecord) -> bool:
    """Return whether an atom record is an actual metal ion.

    This deliberately avoids the common legacy-PDB trap where protein atom names
    such as ``HG`` (gamma hydrogen), ``CD`` (delta carbon), or ``CA`` (alpha
    carbon) are mistaken for Hg, Cd, or Ca when the element column is blank.
    Real metal atoms are accepted from explicit metal residue names, explicit
    HETATM element fields, or atom names that match the residue-level metal ion.
    """

    if atom.element not in METAL_ELEMENTS:
        return False

    residue_identity = METAL_RESIDUE_IDENTITY.get(atom.residue_name)
    if residue_identity is not None:
        return atom.element == residue_identity[0]

    if atom.record_name == "HETATM":
        atom_name = atom.atom_name.strip().upper()
        return atom_name == atom.element or atom_name.startswith(atom.element)

    return False


def _infer_element_from_pdb_fields(
    *,
    record_name: str,
    atom_name: str,
    residue_name: str,
    raw_element: str,
) -> str:
    """Infer element without misreading protein atom names as metals."""

    clean_raw_element = raw_element.strip().upper()
    clean_atom_name = "".join(character for character in atom_name.strip().upper() if character.isalpha())
    clean_residue_name = residue_name.strip().upper()
    clean_record_name = record_name.strip().upper()

    if clean_raw_element:
        return clean_raw_element

    residue_identity = METAL_RESIDUE_IDENTITY.get(clean_residue_name)
    if residue_identity is not None:
        return residue_identity[0]

    # For HETATM records only, accept exact metal-like atom names. This covers
    # stripped component files where the element column was lost. We do not use
    # this rule for ATOM records because atom names such as HG, CD, CA, and FE
    # can be ordinary protein atom names or atom-type-like labels.
    if clean_record_name == "HETATM":
        for length in (2, 1):
            candidate = clean_atom_name[:length]
            if candidate in METAL_ELEMENTS and clean_atom_name == candidate:
                return candidate

    if clean_atom_name.startswith("H"):
        return "H"

    # Common two-letter non-metal elements that can appear in protein/ligand
    # atom names and are not confused with standard protein carbon/hydrogen
    # positional labels.
    for candidate in ("CL", "BR", "SE"):
        if clean_atom_name.startswith(candidate):
            return candidate

    if clean_atom_name[:1] in {"C", "N", "O", "S", "P", "F", "I"}:
        return clean_atom_name[:1]

    return clean_atom_name[:1] if clean_atom_name else ""


def _charge_from_residue_name(residue_name: str) -> int | None:
    identity = METAL_RESIDUE_IDENTITY.get(residue_name.strip().upper())
    if identity is None:
        return None
    return identity[1]


def _parse_pdb_atom_charge(value: str) -> int | None:
    """Parse legacy PDB atom charge columns, e.g. ``2+`` or ``1-``."""

    text = value.strip()
    if not text:
        return None

    if len(text) == 2 and text[0].isdigit() and text[1] in {"+", "-"}:
        magnitude = int(text[0])
        return magnitude if text[1] == "+" else -magnitude

    if len(text) == 2 and text[1].isdigit() and text[0] in {"+", "-"}:
        magnitude = int(text[1])
        return magnitude if text[0] == "+" else -magnitude

    return None


def _ion_label_from_atom(atom: PDBAtomRecord, *, default: str) -> str:
    """Return a compact ion label using explicit or residue-derived charge."""

    charge = atom.formal_charge
    if charge is None:
        return default

    sign = "+" if charge > 0 else "-"
    magnitude = abs(charge)
    return f"{_title_case_element(atom.element)}{magnitude if magnitude != 1 else ''}{sign}"


def _transition_ion_label(atom: PDBAtomRecord) -> str:
    """Return transition-metal ion label without forcing Fe/Cu/Mn to 2+."""

    if atom.formal_charge is not None:
        sign = "+" if atom.formal_charge > 0 else "-"
        magnitude = abs(atom.formal_charge)
        return f"{_title_case_element(atom.element)}{magnitude if magnitude != 1 else ''}{sign}"

    common_unknown = {
        "FE": "Fe(unknown; often Fe2+/Fe3+)",
        "CU": "Cu(unknown; often Cu+/Cu2+)",
        "MN": "Mn(unknown; often Mn2+/Mn3+/Mn4+)",
        "CO": "Co(unknown; often Co2+/Co3+)",
        "NI": "Ni(unknown; often Ni2+)",
        "ZN": "Zn2+",
        "CD": "Cd2+",
        "HG": "Hg2+",
    }
    return common_unknown.get(atom.element, f"{_title_case_element(atom.element)}(transition; charge unknown)")


def _title_case_element(element: str) -> str:
    text = element.strip().upper()
    if len(text) <= 1:
        return text
    return text[0] + text[1:].lower()


def _safe_token(value: str) -> str:
    token = "".join(character if character.isalnum() or character in {"_", "-"} else "_" for character in value.strip())
    return token.strip("_") or "variant"


def _safe_int(value: str, *, default: int) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _safe_float(value: str, *, default: float) -> float:
    try:
        return float(value)
    except Exception:
        return default


def _unique_keep_order(values: list[str] | tuple[str, ...] | set[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        ordered.append(value)
    return ordered