"""Metal classification and geometry checks for FRUTON prepared models.

The module inspects metal atoms in starting structures, component files,
produced FRUTON models, and prepared variants before the final workbook is written. It keeps the policy small:
standard non-transition alkali/alkaline-earth ions are treated as standard-ion
parameter cases, while transition metals are analysed geometrically and flagged
for the metal-parameter branch. Crystal waters are included in the analysis PDB
because crystallographic water molecules frequently complete metal coordination
shells and must not be ignored when deciding the local geometry.

ChimeraX support is deliberately optional. When a ChimeraX executable is found,
this module writes and runs a small contacts script so the contact analysis can
be inspected with the same external tool that a user would use manually. The
structured TSV/JSON output is still generated by deterministic Python distance
analysis, so the pipeline remains usable on machines where ChimeraX is not
installed.
"""

from __future__ import annotations

from pathlib import Path

from stack_protein_preparation.pdb_components import WATER_NAMES as WATER_RESIDUE_NAMES  # noqa: F401 (re-exported)

# Re-export everything from _metalls_check_core so existing imports keep working
from stack_protein_preparation._metalls_check_core import (  # noqa: F401 (re-exported)
    MetalCheckStatus,
    MetalClass,
    DONOR_ELEMENTS,
    TRANSITION_METAL_ELEMENTS,
    METAL_ELEMENTS,
    METAL_RESIDUE_IDENTITY,
    STANDARD_NONTRANSITION_IONS,
    TRANSITION_ION_GEOMETRY_PREFERENCES,
    PDBAtomRecord,
    MetalContact,
    MetalSiteSummary,
    MetalCheckResult,
    find_metal_contacts,
    filter_bidentate_carboxylate_contacts,
    classify_coordination_geometry,
    read_pdb_atom_records,
    summarize_metal_site,
    distance_between_atoms,
    is_true_metal_atom,
    _read_atom_records_with_gemmi,
    _read_atom_records_from_pdb_lines,
    _write_analysis_pdb,
    _parse_pdb_atom_line,
    _run_chimera_contact_script,
    _write_contacts_tsv,
    _write_result_files,
    _angle_for_two_contacts,
    _is_square_planar_like,
    _has_opposite_contact_pair,
    _contact_points_from_labels,
    _angle_between_vectors,
    _pdb_contains_water,
    _pdb_contains_metals,
    _infer_element_from_pdb_fields,
    _charge_from_residue_name,
    _parse_pdb_atom_charge,
    _ion_label_from_atom,
    _transition_ion_label,
    _title_case_element,
    _safe_token,
    _safe_int,
    _safe_float,
    _unique_keep_order,
)


def run_metals_check_for_model(
    *,
    pdb_id: str,
    protein_dir: str | Path,
    variant_label: str,
    model_pdb_path: str | Path,
    metals_pdb_path: str | Path | None = None,
    water_pdb_path: str | Path | None = None,
    output_dir: str | Path | None = None,
    reference_json_path: str | Path | None = None,
    chimera_executable: str | None = None,
    use_chimera: bool = True,
    contact_cutoff_angstrom: float = 3.5,
) -> MetalCheckResult:
    """Classify model metals and write contact/geometry audit artefacts.

    ``model_pdb_path`` should be a produced model or prepared variant, not the raw
    starting PDB. If crystal-water and metal component files are supplied, they
    are appended to the analysis copy when they are not already present. This
    ensures transition-metal coordination analysis sees water donors that may
    complete the coordination shell.
    """

    protein_dir = Path(protein_dir).resolve()
    model_path = Path(model_pdb_path).resolve()
    safe_variant = _safe_token(variant_label)
    resolved_output_dir = (
        Path(output_dir).resolve()
        if output_dir is not None
        else protein_dir / "components" / "metals_check" / safe_variant
    )
    resolved_output_dir.mkdir(parents=True, exist_ok=True)

    analysis_input_path = resolved_output_dir / f"{pdb_id}_{safe_variant}_metal_analysis_input.pdb"
    contacts_tsv_path = resolved_output_dir / f"{pdb_id}_{safe_variant}_metal_contacts.tsv"
    manifest_path = resolved_output_dir / f"{pdb_id}_{safe_variant}_metal_check.json"
    log_path = protein_dir.parent / "logs" / pdb_id / f"metalls_check_{safe_variant}.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    water_path = Path(water_pdb_path).resolve() if water_pdb_path is not None else None
    metals_path = Path(metals_pdb_path).resolve() if metals_pdb_path is not None else None

    _write_analysis_pdb(
        model_pdb_path=model_path,
        output_pdb_path=analysis_input_path,
        water_pdb_path=water_path,
        metals_pdb_path=metals_path,
    )

    atom_records = read_pdb_atom_records(analysis_input_path, source_role="analysis")
    metal_atoms = [atom for atom in atom_records if is_true_metal_atom(atom)]

    chimera_script_path: Path | None = None
    chimera_log_path: Path | None = None
    chimera_status = "skipped"
    if use_chimera and metal_atoms:
        chimera_result = _run_chimera_contact_script(
            analysis_input_path=analysis_input_path,
            output_dir=resolved_output_dir,
            pdb_id=pdb_id,
            variant_label=safe_variant,
            chimera_executable=chimera_executable,
            contact_cutoff_angstrom=contact_cutoff_angstrom,
        )
        chimera_script_path = chimera_result["script_path"]
        chimera_log_path = chimera_result["log_path"]
        chimera_status = chimera_result["status"]

    if not metal_atoms:
        result = MetalCheckResult(
            pdb_id=pdb_id,
            variant_label=variant_label,
            input_model_path=model_path,
            analysis_input_path=analysis_input_path,
            contacts_tsv_path=contacts_tsv_path,
            manifest_path=manifest_path,
            log_path=log_path,
            chimera_script_path=chimera_script_path,
            chimera_log_path=chimera_log_path,
            chimera_status=chimera_status,
            status="skipped",
            metal_class="none",
            ion_type_text="none",
            parameter_reference_text="none",
            found_geometry_text="none",
            probable_geometry_text="none",
            geometry_match="n/a",
            model_metal_ready=True,
            site_summaries=(),
            message="No metal atoms detected in prepared model.",
        )
        _write_contacts_tsv(contacts_tsv_path, ())
        _write_result_files(result)
        return result

    site_summaries = tuple(
        summarize_metal_site(
            metal_atom=metal_atom,
            atom_records=atom_records,
            contact_cutoff_angstrom=contact_cutoff_angstrom,
        )
        for metal_atom in metal_atoms
    )

    all_classes = {site.metal_class for site in site_summaries}
    if all_classes == {"standard_nontransition"}:
        status: MetalCheckStatus = "success"
        metal_class: MetalClass = "standard_nontransition"
        model_metal_ready = True
        message = "Only supported standard non-transition ions detected."
    elif any(site.metal_class == "transition" for site in site_summaries):
        status = "required"
        metal_class = "mixed" if len(all_classes) > 1 else "transition"
        model_metal_ready = False
        message = "Transition-metal site detected; geometry recorded for metal-parameter branch."
    else:
        status = "required"
        metal_class = "unsupported_nontransition"
        model_metal_ready = False
        message = "Unsupported non-transition metal detected; explicit parameters are required."

    geometry_matches = [site.geometry_match for site in site_summaries if site.metal_class == "transition"]
    if geometry_matches:
        geometry_match = "yes" if all(value == "yes" for value in geometry_matches) else "no"
    else:
        geometry_match = "n/a"

    result = MetalCheckResult(
        pdb_id=pdb_id,
        variant_label=variant_label,
        input_model_path=model_path,
        analysis_input_path=analysis_input_path,
        contacts_tsv_path=contacts_tsv_path,
        manifest_path=manifest_path,
        log_path=log_path,
        chimera_script_path=chimera_script_path,
        chimera_log_path=chimera_log_path,
        chimera_status=chimera_status,
        status=status,
        metal_class=metal_class,
        ion_type_text="; ".join(site.ion_label for site in site_summaries),
        parameter_reference_text="; ".join(_unique_keep_order(site.parameter_reference for site in site_summaries)),
        found_geometry_text="; ".join(site.found_geometry for site in site_summaries),
        probable_geometry_text="; ".join(site.probable_geometry for site in site_summaries),
        geometry_match=geometry_match,
        model_metal_ready=model_metal_ready,
        site_summaries=site_summaries,
        message=message,
    )

    all_contacts: list[MetalContact] = []
    for site in site_summaries:
        all_contacts.extend(site.contacts)
    _write_contacts_tsv(contacts_tsv_path, all_contacts)
    _write_result_files(result)
    return result


def run_metals_inventory_for_structure(
    *,
    pdb_id: str,
    protein_dir: str | Path,
    model_pdb_path: str | Path,
    metals_pdb_path: str | Path | None = None,
    water_pdb_path: str | Path | None = None,
    output_dir: str | Path | None = None,
    reference_json_path: str | Path | None = None,
    use_chimera: bool = False,
) -> MetalCheckResult:
    """Run the same metal check as an input inventory.

    This wrapper is intentionally thin. It exists so FRUTON can record metal
    identity and parameter policy immediately after component splitting, even if
    no prepared variant is eventually produced. The check still includes crystal
    waters and separated metal component files when they are available.
    """

    return run_metals_check_for_model(
        pdb_id=pdb_id,
        protein_dir=protein_dir,
        variant_label="input_inventory",
        model_pdb_path=model_pdb_path,
        metals_pdb_path=metals_pdb_path,
        water_pdb_path=water_pdb_path,
        output_dir=output_dir,
        reference_json_path=reference_json_path,
        use_chimera=use_chimera,
    )
