# Auto-generated by metall_params.py
from chimera import runCommand as rc

rc("open tmp_param.pdb")

rc("findclash #0 test other overlap -0.4 hbond 0.0 bondSeparation 2 saveFile contacts.data")

rc("stop now")
