# Auto-generated by metall_params.py
from chimera import runCommand as rc

rc("open tmp_param.pdb")
rc("open metal_only.pdb")

rc("findclash #1 test #0 overlap -0.4 hbond 0.0 bondSeparation 2 saveFile contacts.data")

rc("stop now")
