#!/usr/bin/env python3
"""Aggregate every bench_output/<figure>/PROVENANCE.md into one master table.

Walks bench_output/*/PROVENANCE.md, extracts headline numbers from each
figure's provenance markdown, and emits one reviewer_summary.md +
reviewer_summary.json master roll-up.  Gives a single-file overview of
every real-data reviewer figure the pipeline has produced.

Heuristic extraction rules (deliberately conservative):
- Reads the '## Headline numbers' section (or the first bulleted list
  after any 'Headline' heading).
- Extracts every 'key = value' or 'key: value' line.
- Preserves the figure directory name as the row label.

Usage:
    python scripts/aggregate_reviewer_bench_output.py \\
        --bench-output-dir bench_output/ \\
        --outdir bench_output/

Produces:
    reviewer_summary.md    reviewer-facing markdown roll-up.
    reviewer_summary.json  machine-readable full report.

Pure Python + stdlib.  License-free.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


_HEADLINE_HEADING_RE = re.compile(
    r"^##\s+Headline\s+numbers?\s*(?:\(.*\))?\s*$",
    re.IGNORECASE,
)
_BULLET_LINE_RE = re.compile(r"^\s*[-*]\s+(.+)$")
_NEXT_HEADING_RE = re.compile(r"^#+\s")
_KV_STAR_RE = re.compile(
    r"^\**\s*([A-Za-z][A-Za-z0-9 _/%()\-≤≥Δωαβ]*?)\s*\**\s*[:=]\s*\**(.+?)\**\s*$"
)


def _extract_headline_bullets(path: Path) -> list[str]:
    """Return the list of bullet lines in the first '## Headline numbers'
    section.  Empty list when the section is absent.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    out: list[str] = []
    in_section = False
    for line in lines:
        if _HEADLINE_HEADING_RE.match(line.strip()):
            in_section = True
            continue
        if in_section and _NEXT_HEADING_RE.match(line):
            break
        if in_section:
            m = _BULLET_LINE_RE.match(line)
            if m:
                out.append(m.group(1).strip())
    return out


def _bullet_to_kv(bullet: str) -> tuple[str, str] | None:
    """Convert 'mean clashscore = 2.60 clash pairs / crystal' →
    ('mean clashscore', '2.60 clash pairs / crystal').

    Falls back to None when the bullet has no ':' or '='.
    """
    m = _KV_STAR_RE.match(bullet)
    if not m:
        return None
    return m.group(1).strip(), m.group(2).strip()


def summarise_figure(dir_name: str, provenance_path: Path) -> dict:
    bullets = _extract_headline_bullets(provenance_path)
    headline_kv: dict[str, str] = {}
    freeform: list[str] = []
    for b in bullets:
        kv = _bullet_to_kv(b)
        if kv is None:
            freeform.append(b)
        else:
            headline_kv[kv[0]] = kv[1]
    return {
        "figure_dir": dir_name,
        "provenance_path": str(provenance_path),
        "headline_kv": headline_kv,
        "freeform_bullets": freeform,
    }


def collect_figures(bench_output_dir: Path) -> list[dict]:
    out: list[dict] = []
    for sub in sorted(p for p in bench_output_dir.iterdir() if p.is_dir()):
        prov = sub / "PROVENANCE.md"
        if not prov.is_file():
            continue
        out.append(summarise_figure(sub.name, prov))
    return out


def format_markdown_summary(figures: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Reviewer figures — master summary")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/aggregate_reviewer_bench_output.py` "
        "from the per-figure `PROVENANCE.md` files under `bench_output/`."
    )
    lines.append("")
    lines.append(f"**{len(figures)} figure(s)** currently under `bench_output/`.")
    lines.append("")

    for fig in figures:
        lines.append(f"## {fig['figure_dir']}")
        lines.append("")
        lines.append(f"Provenance: `{fig['provenance_path']}`")
        lines.append("")
        if fig["headline_kv"]:
            lines.append("| Metric | Value |")
            lines.append("|---|---|")
            for k, v in fig["headline_kv"].items():
                # Strip markdown formatting artefacts from the value
                v_clean = v.replace("|", "\\|")
                lines.append(f"| {k} | {v_clean} |")
            lines.append("")
        if fig["freeform_bullets"]:
            lines.append("Freeform bullets:")
            for b in fig["freeform_bullets"]:
                lines.append(f"- {b}")
            lines.append("")
    return "\n".join(lines) + "\n"


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--bench-output-dir", type=Path, default=Path("bench_output"))
    p.add_argument("--outdir", type=Path, default=Path("bench_output"))
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    ns = _parse_args(argv)
    if not ns.bench_output_dir.is_dir():
        print(
            f"[aggregate] ERROR: {ns.bench_output_dir} is not a directory",
            file=sys.stderr,
        )
        return 2

    ns.outdir.mkdir(parents=True, exist_ok=True)
    figures = collect_figures(ns.bench_output_dir)
    if not figures:
        print(
            f"[aggregate] WARNING: no PROVENANCE.md files found under "
            f"{ns.bench_output_dir}",
            file=sys.stderr,
        )

    (ns.outdir / "reviewer_summary.md").write_text(
        format_markdown_summary(figures)
    )
    (ns.outdir / "reviewer_summary.json").write_text(
        json.dumps(figures, indent=2) + "\n"
    )

    print(
        f"[aggregate] {len(figures)} figures aggregated -> "
        f"{ns.outdir / 'reviewer_summary.md'}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
